const URL_FAKE_API =
  "https://raw.githubusercontent.com/StevenGV20/fakeapi-testing/main";
  
const URL_MASTERLOGIC_API = "http://192.168.100.140:5006";
//const URL_MASTERLOGIC_API = "http://192.168.24.246:5006";//http://192.168.1.107:82
const API_MAESTRO = "/api/Maestro";
const API_DISTRIBUCION = "/api/Distribucion";
const API_ORDENES = "/api/OrdenTrabajo/mtl";
const COD_CIA = "01";
const USERNAME_LOCAL = localStorage.getItem("USERNAME");

const GRUPOS_COLS_MODAL_DESKTOP = [
  "GRUPO",
  "SEDE",
  "VOLUMEN TOTAL",
  "MONTO TOTAL",
];

const MANTENIMIENTO_UNIDAD_TRANSPORTE_TABLE_COLS_DESKTOP = [
  "ID",
  "CODIGO",
  "VEHICULO",
  "ORIGEN",
  "CHOFER",
  "CAPACIDAD",
  "",
];

const MANTENIMIENTO_UNIDAD_TRANSPORTE_TABLE_COLS_MOBILE = [
  "UNIDAD DE TRANSPORTE",
  "",
];

const MANTENIMIENTO_RUTAS_TABLE_COLS_DESKTOP = [
  "CODIGO",
  "SEDE",
  "DESCRIPCION",
  "VOLUMEN MINIMO",
  "VOLUMEN MAXIMO",
  "PRECIO",
  "DISTRITOS",
  "",
];
const MANTENIMIENTO_RUTAS_TABLE_COLS_MOBILE = ["RUTA", ""];

const MANTENIMIENTO_RUTAS_DISTRITOS_TABLE_COLS_DESKTOP = [
  "UBIGEO",
  "DISTRITO",
  "",
];
const MANTENIMIENTO_DISTANCIAS_TABLE_COLS_DESKTOP = [
  "SEDE",
  "DISTRITO",
  "KM",
  "",
];

const MANTENIMIENTO_CHOFERES_TABLE_COLS_DESKTOP = [
  "CODIGO",
  "NOMBRE",
  "NRO. LICENCIA",
  "COD. USUARIO",
  "COD. EMPLEADO",
  "NRO. DOCUMENTO",
  "",
];

const MANTENIMIENTO_CHOFERES_TABLE_COLS_MOBILE = ["CHOFER", ""];

const ORDENES_DESPACHO_PARTITION_TABLE_COLS_DESKTOP = [
  "N°",
  "ITEM",
  "CANTIDAD ORIGINAL",
  "CANTIDAD PENDIENTE",
  "CANTIDAD DESPACAHADA",
];

const LUGARES_DESPACHO_TABLE_COLS_DESKTOP = [
  "DIRECCION DE ENTREGA",
  "DEPARTAMENTO",
  "PROVINCIA",
  "DISTRITO",
];
const LUGARES_DESPACHO_TABLE_COLS_MOBILE = ["DIRECCION DE ENTREGA"];

const PEN_CURRENCY = "S/.";
export {
  URL_FAKE_API,
  PEN_CURRENCY,
  ORDENES_DESPACHO_PARTITION_TABLE_COLS_DESKTOP,
  GRUPOS_COLS_MODAL_DESKTOP,
  MANTENIMIENTO_UNIDAD_TRANSPORTE_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_UNIDAD_TRANSPORTE_TABLE_COLS_MOBILE,
  MANTENIMIENTO_RUTAS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_RUTAS_TABLE_COLS_MOBILE,
  MANTENIMIENTO_RUTAS_DISTRITOS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_DISTANCIAS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_CHOFERES_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_CHOFERES_TABLE_COLS_MOBILE,
  LUGARES_DESPACHO_TABLE_COLS_DESKTOP,
  LUGARES_DESPACHO_TABLE_COLS_MOBILE,
  URL_MASTERLOGIC_API,
  API_MAESTRO,
  API_DISTRIBUCION,
  COD_CIA,
  USERNAME_LOCAL,
  API_ORDENES
};
