const PAGE_GENERAR_GRR = "GENERAR GUIA DE REMISIÓN DE REMITENTE";
const PAGE_AGRUPAR_OD = "AGRUPAR ORDEN DE DESPACHO";
const PAGE_AGRUPAR_OD_REATIL = "AGRUPAR ORDEN DE DESPACHO RETAIL";
const IMPORTAR_GUIA_REMISION = "IMPORTAR GUIA REMISION";
const PAGE_ASIGNAR_VEHICULO = "ASIGNAR VEHICULO";
const PAGE_GENERAR_OT_Y_GRT =
  "GENERAR ORDEN DE TRABAJO Y GUIA DE REMISION DE TRANSPORTISTA";
const PAGE_BANDEJA_MARCACIONES = "BANDEJA DE MARCACIONES (OFISIS)"
const PAGE_MANTENIMIENTO_VEHICULOS = "MANTENIMIENTO UNIDADES DE TRANSPORTE";
const PAGE_MANTENIMIENTO_RUTAS = "MANTENIMIENTO RUTAS";
const PAGE_MANTENIMIENTO_DISTRITOS_RUTAS = "MANTENIMIENTO DISTRITOS_RUTAS";
const PAGE_MANTENIMIENTO_DISTANCIAS = "MANTENIMIENTO DISTANCIAS";
const PAGE_MANTENIMIENTO_CHOFERES = "MANTENIMIENTO DE CHOFERES";
const PAGE_LLENADO_OT = "LLENADO DE OTS";
const PAGE_BANDEJA_TAREO = "BANDEJA DE REGISTRO DE HORAS";
const PAGE_PREORDEN = "PRE ORDEN";

export {
  PAGE_GENERAR_GRR,
  PAGE_AGRUPAR_OD,
  PAGE_AGRUPAR_OD_REATIL,
  PAGE_ASIGNAR_VEHICULO,
  PAGE_GENERAR_OT_Y_GRT,
  PAGE_MANTENIMIENTO_VEHICULOS,
  PAGE_MANTENIMIENTO_RUTAS,
  PAGE_MANTENIMIENTO_DISTRITOS_RUTAS,
  PAGE_MANTENIMIENTO_DISTANCIAS,
  PAGE_MANTENIMIENTO_CHOFERES,
  PAGE_BANDEJA_MARCACIONES,
  PAGE_LLENADO_OT,
  PAGE_BANDEJA_TAREO,
  PAGE_PREORDEN,
  IMPORTAR_GUIA_REMISION,
};
